name: Test Extra Headers
on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@master
      - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
      - uses: amondnet/now-deployment@master
        id: now
        with:
          github-comment: false
          zeit-token: ${{ secrets.ZEIT_NOW_TOKEN }}
          now-org-id: ${{ secrets.ZEIT_NOW_ORG_ID }}
          now-project-id: ${{ secrets.ZEIT_NOW_PROJECT_ID }}
      - name: Run Lighthouse
        uses: ./
        with:
          extraHeaders: '{ "Set-Cookie": "USE_COOKIE_CONSENT_STATE={%22session%22:false}; Path=/" }'
          fooApiToken: ${{ secrets.LIGHTHOUSE_CHECK_API_TOKEN }}
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          urlsJson: '[["cf8b27b3-ccb8-4477-83b6-ded2c375f977", "${{ steps.now.outputs.preview-url }}"]]'
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: ${{ github.workspace }}/tmp/artifacts
